version: '3.7'
services:
  database:
    container_name: sqldb
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: Blessing1!
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: products
    ports:
      - "3307:3306"
    networks:
      - backend
  api:
    container_name: go_api
    build: 
      context: ./api
    ports:
      - "8000:8000"
    networks:
      - frontend
      - backend
    depends_on:
      - database
  frontend:
    container_name: front_end
    build:
      context: ./frontend
    ports:
      - "4000:80"
    networks:
      - frontend
    depends_on:
      - database
      - api
networks:
  frontend:
  backend:
